services:
  - type: web
    name: alcohol-tendency-prediction
    runtime: docker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python alcohol_screening_server.py
    pythonVersion: 3.11
